### ISSUE TITLE
Count number of signatures in the image

### ISSUE THREAD

**Issue by seanbenhur** [EnzoSeason/signature_detection#7]
How to count the number of signatures in an image!?

**Comment by EnzoSeason** [comment]
Hi Seanbenhur, there is no specific method to do it. You could calculate it from the return for the method boxes2regions or merge_regions_and_masks of the class Cropper.

**Comment by seanbenhur** [comment]
Thanks for the prompt response, I will try those and update here

**Comment by seanbenhur** [comment]
Well, it didn't work for my images, since some of the signatures are very distorted, I will close the issue for now, Thanks
